const KAVOSH_DATA = {
 "teams": [
  {
   "team": "Box Air",
   "league": "AIR U14",
   "mentor": "Parvin Rezaei",
   "affiliation": "Kavosh",
   "students": [
    {
     "name": "Hoorad Heidari",
     "dob": "2012-11-03",
     "id": "147290",
     "fee": "$516.41",
     "ptag": "p.cnrs",
     "parent": "Niloufar Gheidi",
     "phone": "6476167591",
     "email": "niloufar.gheidi@gmail.com",
     "medical": "",
     "entry": 27,
     "alt_entries": [
      18
     ],
     "prefer": "",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNjbeSn6pElVdKtKoUFIE8EyVfisx6NPm32fvAZuBY4xdIcQLEsx5W9Xu4jiu0xsYZ4",
     "pstatus": 0
    },
    {
     "name": "Arsham Alidoost",
     "dob": "2012-10-02",
     "id": "147291",
     "fee": "$516.41",
     "ptag": "p.cnrs",
     "parent": "Sona Eftekharazam",
     "phone": "4377992465",
     "email": "Sona.eftekharazam@gmail.com",
     "medical": "",
     "entry": 26,
     "alt_entries": [],
     "prefer": "",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNim_DAiZZ3H7mXJX6i3joY7OE0y2Aneza6jQMhmJ1q0k8FHLHh7UyH6OOBlu6S54CM",
     "pstatus": 0
    }
   ]
  },
  {
   "team": "VIC Air Maveric",
   "league": "AIR U14",
   "mentor": "Peyman Yousefi",
   "affiliation": "Victoria - Kavosh",
   "students": [
    {
     "name": "Arianna Kou",
     "dob": "2012-11-02",
     "id": "147286",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Tyler Kou",
     "phone": "6476362753",
     "email": "Tylerkou@gmail.com",
     "medical": "",
     "entry": 20,
     "alt_entries": [],
     "prefer": "",
     "source": "red",
     "form_url": "https://docs.google.com/forms/d/1EQjI3d3AHWtrm38ZgMn3b0Kff7SpVYA-lvt0p-5zPXQ/edit#response=ACYDBNi5BkkM17oOrYLTA21o8q4ZcEYhqk9XwUD9EvfDDpjFDHyywVjw2VkQYicHToz4Qx0",
     "pstatus": 2
    },
    {
     "name": "Arielle Li",
     "dob": "2012-06-08",
     "id": "147287",
     "fee": "$943.55",
     "ptag": "p.kavosh",
     "parent": "FRANK RENJIE LI",
     "phone": "416 669 2952",
     "email": "frank_lrj@hotmail.com",
     "medical": "",
     "entry": 37,
     "alt_entries": [],
     "prefer": "",
     "source": "red",
     "form_url": "https://docs.google.com/forms/d/1EQjI3d3AHWtrm38ZgMn3b0Kff7SpVYA-lvt0p-5zPXQ/edit#response=ACYDBNhoB1EvuDuD_TU3wCNWDk_zFDgCL9ynS4KbcE2tPPSSVjtYqQEbBvyNLPLKCGeV6oo",
     "pstatus": 2
    },
    {
     "name": "Stanley Wang",
     "dob": "2015-10-07",
     "id": "147285",
     "fee": "$1350.35",
     "ptag": "p.cnrs",
     "parent": "Mingxia Zhang",
     "phone": "6477678686",
     "email": "jerrierzhang@gmail.com",
     "medical": "",
     "entry": 23,
     "alt_entries": [],
     "prefer": "",
     "source": "red",
     "form_url": "https://docs.google.com/forms/d/1EQjI3d3AHWtrm38ZgMn3b0Kff7SpVYA-lvt0p-5zPXQ/edit#response=ACYDBNigTc_W7P6GD6ow2in1r5X9KPQ2vYhiSG8ue571EXJ0J22qkH5iHqy5Es4jMHks0Ps",
     "pstatus": 2
    },
    {
     "name": "Stephanie Wang",
     "dob": "2013-06-28",
     "id": "147288",
     "fee": "$1350.35",
     "ptag": "p.cnrs",
     "parent": "Mingxia Zhang",
     "phone": "6477678686",
     "email": "jerrierzhang@gmail.com",
     "medical": "",
     "entry": 22,
     "alt_entries": [],
     "prefer": "",
     "source": "red",
     "form_url": "https://docs.google.com/forms/d/1EQjI3d3AHWtrm38ZgMn3b0Kff7SpVYA-lvt0p-5zPXQ/edit#response=ACYDBNi8QbnlmU9s-VcuuZbRky_d6Q4qptTtVVoCvajpQnceJcUE289FUBH1sM_EGumx7cI",
     "pstatus": 2
    },
    {
     "name": "Shiller Hong",
     "dob": "2014-07-23",
     "id": "147289",
     "fee": "$1350.35",
     "ptag": "p.kavosh",
     "parent": "Jiangnan liu",
     "phone": "6479707968",
     "email": "Clara5883@hotmail.com",
     "medical": "",
     "entry": 28,
     "alt_entries": [],
     "prefer": "",
     "source": "red",
     "form_url": "https://docs.google.com/forms/d/1EQjI3d3AHWtrm38ZgMn3b0Kff7SpVYA-lvt0p-5zPXQ/edit#response=ACYDBNiowHvl2dBTy9XFriK0eITLqA7uvYgBb1oJt_XF5qANmJJbtDWGO0HuLXsXdIwNxRQ",
     "pstatus": 2
    }
   ]
  },
  {
   "team": "VIC Air Eagle",
   "league": "AIR U19",
   "mentor": "Peyman Yousefi",
   "affiliation": "Victoria - Kavosh",
   "students": [
    {
     "name": "Zhiru Chen",
     "dob": "2010-05-28",
     "id": "147851",
     "fee": "$3500",
     "ptag": "p.cnrs",
     "parent": "",
     "phone": "",
     "email": "",
     "medical": "",
     "entry": null,
     "alt_entries": [],
     "source": null,
     "form_url": "",
     "pstatus": 3
    },
    {
     "name": "Andrew Liu",
     "dob": "2012-03-12",
     "id": "147284",
     "fee": "$1350.35",
     "ptag": "p.cnrs",
     "parent": "Yuzhan He",
     "phone": "6478016885",
     "email": "rena_louisa_he@yahoo.com",
     "medical": "",
     "entry": 63,
     "alt_entries": [],
     "prefer": "Andrew",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNilFliC-oD4LTPxZ_HinzB8NSmTq50ksl-WKzzKigopm8-NZQfVpUSGQGVJ4fUc5X4",
     "pstatus": 0
    },
    {
     "name": "Kevin Gao",
     "dob": "2011-11-10",
     "id": "147294",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Ying Tan",
     "phone": "6475055189",
     "email": "labying@gmail.com",
     "medical": "",
     "entry": 45,
     "alt_entries": [],
     "prefer": "Kevin",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNj-N5rNA7P-h5BKCEe86qivQRvNrd8wSgAynOTWnBVgZ7-NJA70-nKPs1VdHB9KXp4",
     "pstatus": 0
    },
    {
     "name": "David Zhou",
     "dob": "2013-04-24",
     "id": "147295",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Qi Zhang",
     "phone": "647-855-0619",
     "email": "sarah.qi.zhang@gmail.com",
     "medical": "",
     "entry": 62,
     "alt_entries": [],
     "prefer": "",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNg5jVBU9frHLm1-CfY-amNs1ZKJz1--hdJ7TKsOx8lDu6iq67kysE_8RpWygi2I3Tc",
     "pstatus": 0
    },
    {
     "name": "Peter Lyu",
     "dob": "2011-01-21",
     "id": "147845",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "baosen Lu",
     "phone": "6478673568",
     "email": "baosen3568@gmail.com",
     "medical": "",
     "entry": 38,
     "alt_entries": [],
     "prefer": "Peter",
     "source": "red",
     "form_url": "https://docs.google.com/forms/d/1EQjI3d3AHWtrm38ZgMn3b0Kff7SpVYA-lvt0p-5zPXQ/edit#response=ACYDBNgmPONw3RcSWSMvzqUhAEHtAoKILxLMVw6qWFJEet5tDMRqtYl3Q-GRMZwUKssckWI",
     "pstatus": 2
    },
    {
     "name": "Sam Jinkang Liu",
     "dob": "2010-01-10",
     "id": "147293",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Jie Zhang",
     "phone": "647-466-3958",
     "email": "Jessicazj730@gmail.com",
     "medical": "",
     "entry": 49,
     "alt_entries": [],
     "prefer": "Sam liu",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNh2UTHeeX9N5XUx3iTcFlqv_5tfDalDHP2be2_-yxe9Z75n5VkJf60GLuQKV1NbkMI",
     "pstatus": 0
    }
   ]
  },
  {
   "team": "Box Business Bright",
   "league": "Business U14",
   "mentor": "Sina Tavosli",
   "affiliation": "Kavosh",
   "students": [
    {
     "name": "Payam Norouzi",
     "dob": "2015-02-14",
     "id": "147300",
     "fee": "$0",
     "ptag": "p.cnrs",
     "parent": "Asadollah Norouzi",
     "phone": "416-938-0702",
     "email": "asad.norouzi@gmail.com",
     "medical": "",
     "entry": 28,
     "alt_entries": [],
     "prefer": "Payam",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNgyyfMZvUJQGOEMFvYMH231W7ez63ika28rp8HeIH3Bua43YeS-mmYmmVl9LQDa0Xc",
     "pstatus": 0
    },
    {
     "name": "Ariyan Zangooei",
     "dob": "2015-05-29",
     "id": "147298",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Dr.Behrooz Zangooei",
     "phone": "416-834-6373",
     "email": "behrooz77@gmail.com",
     "medical": "",
     "entry": 25,
     "alt_entries": [],
     "prefer": "Ariyan",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNinDv6BgXrH3EjjEtAj4SStF-tVUy8XTx8TtA65PwJK6WS8xiPcIphH5WiYJxCAaT0",
     "pstatus": 0
    },
    {
     "name": "Nika Kashani",
     "dob": "2014-09-11",
     "id": "147299",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Mahkameh kouladji",
     "phone": "4168776156",
     "email": "mahkamehk@gmail.com",
     "medical": "",
     "entry": 23,
     "alt_entries": [],
     "prefer": "Nika",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNhSu35hwa6rkb-aumjXWSL2j-YKGDcDayrSDa9p-jk632rz7sZdhnjIj7q--nli68E",
     "pstatus": 0
    },
    {
     "name": "Seyyed Shayan Mirkhani",
     "dob": "2014-01-04",
     "id": "147296",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Mahsa Movahedi Meimandi",
     "phone": "647 870 9773",
     "email": "mahsa.movahedi@gmail.com",
     "medical": "",
     "entry": 24,
     "alt_entries": [],
     "prefer": "Shayan",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNjjtLfBM30v881Av59-PybiIbufoUE07dYDPl5t_9KBOwMGaP4mPKgAfs8fM9W3dYc",
     "pstatus": 0
    }
   ]
  },
  {
   "team": "Business Apex",
   "league": "Business U19",
   "mentor": "Peyman Yousefi",
   "affiliation": "Kavosh",
   "students": [
    {
     "name": "Kingsley Guanqun,Wu",
     "dob": "",
     "id": "147328",
     "fee": "",
     "ptag": "",
     "parent": "Guo Wu",
     "phone": "7788636358",
     "email": "derekwu13@gmail.com",
     "medical": "Nuts allergy",
     "entry": 40,
     "alt_entries": [
      39
     ],
     "prefer": "",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNjr3TND2C6vzwLk1qDFdl8XmV2qBqSsYz_x0M_A18nGP8i3bRc3CIYZdvbVPmFhJQo",
     "pstatus": 0
    },
    {
     "name": "Benjamin Han",
     "dob": "2010-12-12",
     "id": "147327",
     "fee": "$10000",
     "ptag": "p.cnrs",
     "parent": "",
     "phone": "",
     "email": "",
     "medical": "",
     "entry": null,
     "alt_entries": [],
     "source": null,
     "form_url": "",
     "pstatus": 3
    },
    {
     "name": "Jiale Zhao",
     "dob": "2008-12-30",
     "id": "147850",
     "fee": "$6200",
     "ptag": "p.cnrs",
     "parent": "Kai Zhao",
     "phone": "+1 (437) 556 9955",
     "email": "yashu.hoop@gmail.com",
     "medical": "",
     "entry": 59,
     "alt_entries": [],
     "prefer": "Jerry",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNg2aLKYS-96HNka3q6HLrkqG65HPbFn_unoRTlDDivnYNA-3lFhMWpxnz5IoMTUn3o",
     "pstatus": 0
    },
    {
     "name": "Zhiheng Li",
     "dob": "2011-08-06",
     "id": "147859",
     "fee": "$6200",
     "ptag": "p.cnrs",
     "parent": "",
     "phone": "",
     "email": "",
     "medical": "",
     "entry": null,
     "alt_entries": [],
     "source": null,
     "form_url": "",
     "pstatus": 3
    }
   ]
  },
  {
   "team": "Box Mission Bright",
   "league": "Mission U14",
   "mentor": "Ali Zakerynejad",
   "affiliation": "Kavosh",
   "students": [
    {
     "name": "Shuning Yang",
     "dob": "2013-10-28",
     "id": "147852",
     "fee": "$3850",
     "ptag": "p.cnrs",
     "parent": "",
     "phone": "",
     "email": "",
     "medical": "",
     "entry": null,
     "alt_entries": [],
     "source": null,
     "form_url": "",
     "pstatus": 3
    },
    {
     "name": "Seyyed Shayan Mirkhani",
     "dob": "2014-01-04",
     "id": "147296",
     "fee": "0",
     "ptag": "p.cnrs",
     "parent": "Mahsa Movahedi Meimandi",
     "phone": "647 870 9773",
     "email": "mahsa.movahedi@gmail.com",
     "medical": "",
     "entry": 24,
     "alt_entries": [],
     "prefer": "Shayan",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNjjtLfBM30v881Av59-PybiIbufoUE07dYDPl5t_9KBOwMGaP4mPKgAfs8fM9W3dYc",
     "pstatus": 0
    },
    {
     "name": "Ariyan Zangooei",
     "dob": "2015-05-29",
     "id": "147298",
     "fee": "0",
     "ptag": "p.cnrs",
     "parent": "Dr.Behrooz Zangooei",
     "phone": "416-834-6373",
     "email": "behrooz77@gmail.com",
     "medical": "",
     "entry": 25,
     "alt_entries": [],
     "prefer": "Ariyan",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNinDv6BgXrH3EjjEtAj4SStF-tVUy8XTx8TtA65PwJK6WS8xiPcIphH5WiYJxCAaT0",
     "pstatus": 0
    },
    {
     "name": "Nika Kashani",
     "dob": "2014-09-11",
     "id": "147299",
     "fee": "0",
     "ptag": "p.cnrs",
     "parent": "Mahkameh kouladji",
     "phone": "4168776156",
     "email": "mahkamehk@gmail.com",
     "medical": "",
     "entry": 23,
     "alt_entries": [],
     "prefer": "Nika",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNhSu35hwa6rkb-aumjXWSL2j-YKGDcDayrSDa9p-jk632rz7sZdhnjIj7q--nli68E",
     "pstatus": 0
    }
   ]
  },
  {
   "team": "Box Mission Smart",
   "league": "Mission U14",
   "mentor": "Parvin Rezaei",
   "affiliation": "Kavosh",
   "students": [
    {
     "name": "Payam Norouzi",
     "dob": "2015-02-14",
     "id": "147300",
     "fee": "$0",
     "ptag": "p.cnrs",
     "parent": "Asadollah Norouzi",
     "phone": "416-938-0702",
     "email": "asad.norouzi@gmail.com",
     "medical": "",
     "entry": 28,
     "alt_entries": [],
     "prefer": "Payam",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNgyyfMZvUJQGOEMFvYMH231W7ez63ika28rp8HeIH3Bua43YeS-mmYmmVl9LQDa0Xc",
     "pstatus": 0
    },
    {
     "name": "Sam Yazdanbakhsh",
     "dob": "2016-01-31",
     "id": "147301",
     "fee": "$516.41",
     "ptag": "p.kavosh",
     "parent": "",
     "phone": "",
     "email": "",
     "medical": "",
     "entry": null,
     "alt_entries": [],
     "source": null,
     "form_url": "",
     "pstatus": 3
    },
    {
     "name": "Artin Adeli",
     "dob": "2015-10-20",
     "id": "147302",
     "fee": "$516.41",
     "ptag": "p.kavosh",
     "parent": "Yasaman Motakef",
     "phone": "416-839-9392",
     "email": "",
     "medical": "",
     "entry": null,
     "alt_entries": [],
     "source": null,
     "form_url": "",
     "pstatus": 1
    },
    {
     "name": "Sam Farshadi",
     "dob": "2015-08-15",
     "id": "147846",
     "fee": "$516.41",
     "ptag": "p.kavosh",
     "parent": "Mohadeseh Golparvar",
     "phone": "647-939-6433",
     "email": "goligolparvar.ca@gmail.com",
     "medical": "",
     "entry": null,
     "alt_entries": [],
     "source": null,
     "form_url": "",
     "pstatus": 1
    }
   ]
  },
  {
   "team": "Global Mission",
   "league": "Mission U14",
   "mentor": "Ali Zakerynejad",
   "affiliation": "Global Link - Kavosh",
   "students": [
    {
     "name": "Amirsam Ghalamshahi",
     "dob": "2011-05-27",
     "id": "147317",
     "fee": "",
     "ptag": "",
     "parent": "",
     "phone": "",
     "email": "",
     "medical": "",
     "entry": null,
     "alt_entries": [],
     "source": null,
     "form_url": "",
     "pstatus": 3
    },
    {
     "name": "Shahrokh Reihani",
     "dob": "2011-02-01",
     "id": "147311",
     "fee": "$516.41",
     "ptag": "p.cnrs",
     "parent": "Bahador Reihani",
     "phone": "4376692920",
     "email": "b.reihani78@gmail.com",
     "medical": "",
     "entry": 20,
     "alt_entries": [],
     "prefer": "Shahrokh",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNgdANnEQfLSFi56BG5gKsz3egq1UCJHsIaSI7YM9pp7oCWpc-CDpoRdIr99drUt3PI",
     "pstatus": 0
    },
    {
     "name": "Shahriar Reihani",
     "dob": "2013-01-08",
     "id": "147312",
     "fee": "$516.41",
     "ptag": "p.cnrs",
     "parent": "Bahador Reihani",
     "phone": "4376692920",
     "email": "b.reihani78@gmail.com",
     "medical": "",
     "entry": 21,
     "alt_entries": [],
     "prefer": "Shahriar",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNifamPyXuLRlPrc4kvhV3jTSvW9JhnAFfMzCYWRfX43MCIF-xvmVAvvH7SF9KE2E30",
     "pstatus": 0
    },
    {
     "name": "Radin Ghajari",
     "dob": "2015-01-02",
     "id": "147313",
     "fee": "$516.41",
     "ptag": "p.cnrs",
     "parent": "Alireza Ghajari",
     "phone": "6478536943",
     "email": "Alirezaghajari.ag@gmail.com",
     "medical": "",
     "entry": 32,
     "alt_entries": [],
     "prefer": "Radin",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNgi0ktH8QNEXXNY9lM0s8uClsNWhApQKnA_1WAE-b_oHKqFs-7JNHpRq2G77Icq-2A",
     "pstatus": 0
    },
    {
     "name": "Aaron Wang",
     "dob": "2014-07-12",
     "id": "147318",
     "fee": "$943.55",
     "ptag": "p.kavosh",
     "parent": "Jun Wang",
     "phone": "6477876696",
     "email": "kevinjunwang@gmail.com",
     "medical": "",
     "entry": 46,
     "alt_entries": [],
     "prefer": "Aaron",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNgWHNM0h5LX7uU5ceTgN9ZZsPThDQwowrONHjCcqLIamcwprxbB-MgXn74nHDlAOoI",
     "pstatus": 0
    }
   ]
  },
  {
   "team": "VIC Mission Challenger",
   "league": "Mission U14",
   "mentor": "Parvin Rezaei",
   "affiliation": "Victoria - Kavosh",
   "students": [
    {
     "name": "Kiasha Zarabadipour",
     "dob": "2016-08-15",
     "id": "147847",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Mehrnaz Jalalian",
     "phone": "4372481185",
     "email": "m.jalalian508@gmail.com",
     "medical": "",
     "entry": 51,
     "alt_entries": [
      19
     ],
     "prefer": "",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNjLtnDrJSO6L57ujCijyayyvnD-4cC5BghsjfAdfYz2vrHJWSyhjoCQNJvTlXQW0-E",
     "pstatus": 0
    },
    {
     "name": "ANNIE ZHANGLONGYUE",
     "dob": "2016-05-07",
     "id": "147315",
     "fee": "$943.55",
     "ptag": "p.kavosh",
     "parent": "LIANLIAN",
     "phone": "4378781319",
     "email": "Kriss131419@gmail.com",
     "medical": "",
     "entry": 14,
     "alt_entries": [],
     "prefer": "",
     "source": "red",
     "form_url": "https://docs.google.com/forms/d/1EQjI3d3AHWtrm38ZgMn3b0Kff7SpVYA-lvt0p-5zPXQ/edit#response=ACYDBNj811L1P81ym0wl1IBCaN16UqZLT6vTjozdwOyRokClHV8qITeJN9R26nXLqyh6R5g",
     "pstatus": 2
    },
    {
     "name": "Anson Chen",
     "dob": "2016-11-20",
     "id": "147316",
     "fee": "$943.55",
     "ptag": "p.kavosh",
     "parent": "Wenshu Wang",
     "phone": "6472843288",
     "email": "susanwang201204@gmail.com",
     "medical": "Peanut",
     "entry": 61,
     "alt_entries": [],
     "prefer": "Anson Chen",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNgOuU1vtNgdZEtaG4dO3Y0e-zyZbUCVcMQCfPRqc9VADy7052l_UMU9xsJ7yt_u0SE",
     "pstatus": 0
    },
    {
     "name": "Yuqian Song",
     "dob": "2015-06-03",
     "id": "147314",
     "fee": "$1350.35",
     "ptag": "p.kavosh",
     "parent": "YINGQIAO SONG",
     "phone": "647-962-8678",
     "email": "bridge.song@gmail.com",
     "medical": "",
     "entry": 56,
     "alt_entries": [],
     "prefer": "Rain",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNj0X61Cfkt-leUxeYSKuaeONT4qIl3uauqIOA_9Yp-cFnLUTaTh5K9TF6p9T44UoVk",
     "pstatus": 0
    },
    {
     "name": "Nikan Kalantari",
     "dob": "2017-02-19",
     "id": "147848",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Seyed Meisam Kalantari",
     "phone": "6478091184",
     "email": "maysam.kalantari@gmail.com",
     "medical": "",
     "entry": 22,
     "alt_entries": [],
     "prefer": "Nikan",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNhxLNWubfo9Mr5MXcmU88dz3cYXhlI4rzC7-e8bLJzhihDKvMxe0f88Hh5B20gmxOg",
     "pstatus": 0
    }
   ]
  },
  {
   "team": "VIC Mission Nova",
   "league": "Mission U14",
   "mentor": "Ali Zakerynejad",
   "affiliation": "Victoria - Kavosh",
   "students": [
    {
     "name": "Abbi Lyn Gonsalves",
     "dob": "2013-02-20",
     "id": "147320",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Hairong wang",
     "phone": "6478913028",
     "email": "Haowendy999@gmail.com",
     "medical": "",
     "entry": 34,
     "alt_entries": [],
     "prefer": "",
     "source": "red",
     "form_url": "https://docs.google.com/forms/d/1EQjI3d3AHWtrm38ZgMn3b0Kff7SpVYA-lvt0p-5zPXQ/edit#response=ACYDBNiu4jWNZ0uBTPpsCVZP03IsM1G_RqoPvEREy8-MvCE_G9HMD1VBaJBd0iIBlV7gBG0",
     "pstatus": 2
    },
    {
     "name": "Shuli Guo",
     "dob": "2012-10-08",
     "id": "147321",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Zonglan Guo",
     "phone": "4372986699",
     "email": "leoguowin@gmail.com",
     "medical": "",
     "entry": 29,
     "alt_entries": [],
     "prefer": "",
     "source": "red",
     "form_url": "https://docs.google.com/forms/d/1EQjI3d3AHWtrm38ZgMn3b0Kff7SpVYA-lvt0p-5zPXQ/edit#response=ACYDBNh4qOrQATA4zS8V8babEjMlcS566Rh1JJU1g8IYTSOI5acVTMUbQPQT4hnDBhCTH-c",
     "pstatus": 2
    },
    {
     "name": "Jonathan Yin",
     "dob": "2016-09-14",
     "id": "147322",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Jia Liao",
     "phone": "6479962180",
     "email": "amyliao26@gmail.com",
     "medical": "",
     "entry": 52,
     "alt_entries": [],
     "prefer": "Jonathan Yin",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNiAct1G0K2NK3--fqVdkbsHtpO8blO3dFOBjNO2iNbdVNWb0GKbG1A31YxTzWc885Q",
     "pstatus": 0
    },
    {
     "name": "Claire Wang",
     "dob": "2016-06-21",
     "id": "147319",
     "fee": "$943.55",
     "ptag": "p.kavosh",
     "parent": "Jun Wang",
     "phone": "6477876696",
     "email": "kevinjunwang@gmail.com",
     "medical": "",
     "entry": 50,
     "alt_entries": [],
     "prefer": "Claire",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNjTwm7R-S7fUFOru70N3WE39chh22Q1GPwQrodwXHoz3fpE6vGVTCVIjor0ygs27nw",
     "pstatus": 0
    }
   ]
  },
  {
   "team": "VIC Mission Titan",
   "league": "Mission U14",
   "mentor": "Ali Zakerynejad",
   "affiliation": "Victoria - Kavosh",
   "students": [
    {
     "name": "Leona Wang",
     "dob": "2014-10-31",
     "id": "147323",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Zhenkai Wang",
     "phone": "5144767380",
     "email": "hunterwang1986@gmail.com",
     "medical": "",
     "entry": 55,
     "alt_entries": [],
     "prefer": "",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNhrhYbNurDjKv4pu9y_9CdvlySWQPlUICuSs1KlIzvnGZZB6cSFGzScFA6nRTg_120",
     "pstatus": 0
    },
    {
     "name": "William Wang",
     "dob": "2017-03-10",
     "id": "147324",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Zh en kai Wang",
     "phone": "5144767380",
     "email": "hunterwang1986@gmail.com",
     "medical": "",
     "entry": 57,
     "alt_entries": [],
     "prefer": "",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNhsq_5vQIAmbxLSUp2ioI8fR5UM6QdG5TTCYV9Jv3sP6r7FjFm5Yr5gd0Yrom42WSs",
     "pstatus": 0
    },
    {
     "name": "Annabelle Lam",
     "dob": "2013-05-14",
     "id": "147325",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Shan Jiang",
     "phone": "6479980996",
     "email": "Sjiang06@gmail.com",
     "medical": "Birch tree pollen allergy",
     "entry": 47,
     "alt_entries": [],
     "prefer": "Annabelle",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNjbdn7VaC3qaZma_5wIQhY71CSdjPueSLdBVb29cit_-DDGFUQ6Aei6uRVTPigiJUs",
     "pstatus": 0
    },
    {
     "name": "Alice Lam",
     "dob": "2016-08-23",
     "id": "147849",
     "fee": "$943.55",
     "ptag": "p.cnrs",
     "parent": "Shan Jiang",
     "phone": "6479980996",
     "email": "Sjiang06@gmail.com",
     "medical": "Hazel Nut alergy",
     "entry": 48,
     "alt_entries": [],
     "prefer": "Alice",
     "source": "purple",
     "form_url": "https://docs.google.com/forms/d/1RTs2BP43HmaEWfQrDPbwxL4uLbvBV7lpqfK_pCfRc2A/edit#response=ACYDBNjBVoua12VnWTNmjoxqhxR9qqabE_TLLLCR-SkaSeMHbu2dOnJlfi09ITvgAIGIO8w",
     "pstatus": 0
    }
   ]
  }
 ],
 "volunteers": [
  {
   "name": "Tia Li",
   "age": 15,
   "note": "Cannot attend until the 13th; beef/egg allergy; fluent Mandarin"
  },
  {
   "name": "Syed Rizvi",
   "age": 16,
   "note": "No coding experience"
  },
  {
   "name": "Zihao (Zachary) Chen",
   "age": 16,
   "note": "Strong coding experience; 1000+ volunteer hrs"
  },
  {
   "name": "Nireson George",
   "age": 15,
   "note": "No coding experience"
  },
  {
   "name": "Aiden Chang",
   "age": 16,
   "note": "FIRST robotics club; no coding experience"
  },
  {
   "name": "Andrew Macdonald",
   "age": 36,
   "note": "$700 reimbursement; game design major; coach certificate"
  },
  {
   "name": "Aiyman Moroud",
   "age": 30,
   "note": "Robotics major; coach certificate"
  },
  {
   "name": "Kevin Tran",
   "age": 26,
   "note": "Cybersecurity; teaching experience; coach certificate"
  }
 ],
 "unmatched": [
  {
   "entry": 1,
   "parent": "Weihua Zhuang",
   "email": "bbpicc@hotmail.com",
   "phone": "778 892 9588",
   "student": "Justin Xinyan Xing",
   "prefer": "Justin",
   "medical": "",
   "initial": "Weihua Zhuang",
   "submitted": "3/31/26, 12:06 AM"
  },
  {
   "entry": 2,
   "parent": "Xian Chen",
   "email": "purity_chen160@hotmail.com",
   "phone": "7788589277",
   "student": "Celine yueyan Chen",
   "prefer": "Celine",
   "medical": "",
   "initial": "Cx",
   "submitted": "4/3/26, 1:52 PM"
  },
  {
   "entry": 3,
   "parent": "Reza Saadatmand",
   "email": "rez.saadatmand@gmail.com",
   "phone": "6048348269",
   "student": "Rigel Mason Saadatmand",
   "prefer": "Rigel",
   "medical": "",
   "initial": "Reza Saadatmand",
   "submitted": "4/3/26, 4:53 PM"
  },
  {
   "entry": 4,
   "parent": "Jinping Luo",
   "email": "Aileen.luo891@gmail.com",
   "phone": "514-885-5890",
   "student": "Louis Zhengxuan Yu",
   "prefer": "Louis Yu",
   "medical": "None",
   "initial": "JpL",
   "submitted": "4/7/26, 6:43 PM"
  },
  {
   "entry": 5,
   "parent": "LUYAO Chen",
   "email": "iamrebecca11@yahoo.com",
   "phone": "5149696546",
   "student": "Ryan Tran",
   "prefer": "",
   "medical": "None",
   "initial": "LUYAO CHEN",
   "submitted": "4/7/26, 7:14 PM"
  },
  {
   "entry": 6,
   "parent": "Yizhen Liu",
   "email": "Yizhenliu512@gmail.com",
   "phone": "5146928878",
   "student": "Brian Liu Chen",
   "prefer": "Brian",
   "medical": "None",
   "initial": "Yizhen Liu",
   "submitted": "4/7/26, 7:52 PM"
  },
  {
   "entry": 7,
   "parent": "Frank Liu",
   "email": "frankchengliu@gmail.com",
   "phone": "514-983-8858",
   "student": "Kenneth Liu",
   "prefer": "Kenneth",
   "medical": "None",
   "initial": "Frank Liu",
   "submitted": "4/8/26, 12:05 AM"
  },
  {
   "entry": 8,
   "parent": "Zhuo Miao",
   "email": "joyo_miao@hotmail.com",
   "phone": "5147466718",
   "student": "Samuel Zhang",
   "prefer": "Samuel",
   "medical": "None",
   "initial": "MZ",
   "submitted": "4/8/26, 8:42 AM"
  },
  {
   "entry": 9,
   "parent": "Xiumin Du",
   "email": "Duxiumin@gmail.com",
   "phone": "416-3882568",
   "student": "William Mei",
   "prefer": "",
   "medical": "None",
   "initial": "XD",
   "submitted": "4/8/26, 7:55 PM"
  },
  {
   "entry": 10,
   "parent": "Mina Mohammadkhorasani",
   "email": "M_mohamadkhorasani@yahoo.com",
   "phone": "7783258790",
   "student": "Rayan Hesari",
   "prefer": "Rayan",
   "medical": "None",
   "initial": "mm",
   "submitted": "4/9/26, 12:46 PM"
  },
  {
   "entry": 11,
   "parent": "xinfeng zhang",
   "email": "zhxfcn@hotmail.com",
   "phone": "6478818859",
   "student": "Stephan Zhang",
   "prefer": "",
   "medical": "None",
   "initial": "xfzhang",
   "submitted": "4/9/26, 9:47 PM"
  },
  {
   "entry": 12,
   "parent": "xinfeng zhang",
   "email": "zhxfcn@hotmail.com",
   "phone": "6478818859",
   "student": "Stephan Zhang",
   "prefer": "",
   "medical": "None",
   "initial": "xfzhang",
   "submitted": "4/9/26, 10:01 PM"
  },
  {
   "entry": 13,
   "parent": "Pariya Akbarian",
   "email": "akbarian.p@gmail.com",
   "phone": "4376678808",
   "student": "Hirad Sadat mansouri",
   "prefer": "Hirad",
   "medical": "None",
   "initial": "PAS",
   "submitted": "4/10/26, 8:20 AM"
  },
  {
   "entry": 14,
   "parent": "Elham shomali nezhad / Sina Farizi",
   "email": "Elham.232@gmail.com",
   "phone": "647-679-2775",
   "student": "Rayan Farizi",
   "prefer": "",
   "medical": "None",
   "initial": "Elham shomali nezhad",
   "submitted": "4/11/26, 4:24 PM"
  },
  {
   "entry": 15,
   "parent": "Mohammad Mohammadi",
   "email": "M-mm@live.com",
   "phone": "6475506090",
   "student": "Daarya Mohammadi",
   "prefer": "",
   "medical": "None",
   "initial": "M.Mohammadi",
   "submitted": "4/14/26, 3:03 PM"
  },
  {
   "entry": 16,
   "parent": "Ali Baladi",
   "email": "alibaladi.aut@gmail.com",
   "phone": "6048166120",
   "student": "Liam Baladi",
   "prefer": "",
   "medical": "None",
   "initial": "AB",
   "submitted": "4/20/26, 3:42 PM"
  },
  {
   "entry": 17,
   "parent": "Davood Yaali",
   "email": "davood.yaali@gmail.com",
   "phone": "4372560071",
   "student": "Daniel Yaali",
   "prefer": "Daniel",
   "medical": "None",
   "initial": "Davood Yaali",
   "submitted": "4/21/26, 5:58 PM"
  },
  {
   "entry": 29,
   "parent": "Shadi Ansari",
   "email": "ansarishadi90@gmail.com",
   "phone": "6048163069",
   "student": "Liam Baladi",
   "prefer": "",
   "medical": "None",
   "initial": "Shadi Ansari",
   "submitted": "5/30/26, 6:57 PM"
  },
  {
   "entry": 30,
   "parent": "Reza Saadatmand",
   "email": "rez.saadatmand@gmail.com",
   "phone": "604-834-8269",
   "student": "Rigel Mason Saadatmand",
   "prefer": "",
   "medical": "None",
   "initial": "R.S.",
   "submitted": "5/30/26, 7:20 PM"
  },
  {
   "entry": 31,
   "parent": "Maryam kianidoust",
   "email": "farnaz.kiani@gmail.com",
   "phone": "6474000170",
   "student": "Shanar mojaverian",
   "prefer": "Shanar",
   "medical": "None",
   "initial": "Maryam kianidoust",
   "submitted": "5/30/26, 7:28 PM"
  },
  {
   "entry": 33,
   "parent": "Li Yuan",
   "email": "wendyyuan82233@gmail.com",
   "phone": "7787089661",
   "student": "Brayan zhang",
   "prefer": "brayan",
   "medical": "None",
   "initial": "Ly",
   "submitted": "6/6/26, 10:32 AM"
  },
  {
   "entry": 34,
   "parent": "Li Yuan",
   "email": "wendyyuan82233@gmail.com",
   "phone": "7787089661",
   "student": "Brayan Qingyuan Zhang",
   "prefer": "Brayan",
   "medical": "None",
   "initial": "ly",
   "submitted": "6/14/26, 8:50 PM"
  },
  {
   "entry": 35,
   "parent": "Jean Liu",
   "email": "ljing199882@gmail.com",
   "phone": "7789994462",
   "student": "MaxLiao",
   "prefer": "",
   "medical": "None",
   "initial": "ye s",
   "submitted": "6/14/26, 10:28 PM"
  },
  {
   "entry": 36,
   "parent": "Sara Akbarihamed",
   "email": "sarakeshmiri58@gmail.com",
   "phone": "2369831282",
   "student": "Roza Keshmiri",
   "prefer": "",
   "medical": "None",
   "initial": "Sara Akbarihamed",
   "submitted": "6/15/26, 4:21 PM"
  },
  {
   "entry": 37,
   "parent": "Bingyu LIU",
   "email": "brand_new_sharon@yahoo.com",
   "phone": "7789960794",
   "student": "SAI GONG",
   "prefer": "",
   "medical": "None",
   "initial": "BL",
   "submitted": "6/15/26, 5:56 PM"
  },
  {
   "entry": 38,
   "parent": "Nazanin Hesami Takaloo",
   "email": "Hesaminazanin1365@gmail.com",
   "phone": "6478677744",
   "student": "Kourosh Doorandish Yazdi",
   "prefer": "Kourosh",
   "medical": "None",
   "initial": "N.H",
   "submitted": "6/16/26, 7:37 PM"
  },
  {
   "entry": 41,
   "parent": "Robert James Loe",
   "email": "robertjloe@outlook.com",
   "phone": "7788470312",
   "student": "Ethan James Loe",
   "prefer": "Ethan",
   "medical": "None",
   "initial": "rl",
   "submitted": "6/17/26, 8:11 PM"
  },
  {
   "entry": 42,
   "parent": "Xin Lu",
   "email": "sunnyloo@163.com",
   "phone": "7785593322",
   "student": "Delun Zang",
   "prefer": "Allen Zang",
   "medical": "None",
   "initial": "Xin Lu",
   "submitted": "6/17/26, 8:22 PM"
  },
  {
   "entry": 43,
   "parent": "Qianjia Zhou",
   "email": "446527682@qq.com",
   "phone": "6725512510",
   "student": "Xuanlong William Lu",
   "prefer": "William",
   "medical": "None",
   "initial": "Qianjia Zhou",
   "submitted": "6/17/26, 8:28 PM"
  },
  {
   "entry": 44,
   "parent": "Chun Feng",
   "email": "alyssa.cf.bc@gmail.com",
   "phone": "6727791888",
   "student": "Muzhi Shi",
   "prefer": "George",
   "medical": "None",
   "initial": "CF",
   "submitted": "6/19/26, 11:56 PM"
  },
  {
   "entry": 53,
   "parent": "Elham shomali nezhad",
   "email": "elham.232@gmail.com",
   "phone": "647-679-2775",
   "student": "Rayan Farizi",
   "prefer": "",
   "medical": "None",
   "initial": "ES",
   "submitted": "6/23/26, 4:37 PM"
  },
  {
   "entry": 54,
   "parent": "Mina Mohammadkhorasani",
   "email": "M_mohamadkhorasani@yahoo.com",
   "phone": "7783258790",
   "student": "Rayan Hesari",
   "prefer": "Rayan",
   "medical": "None",
   "initial": "Mm",
   "submitted": "6/23/26, 5:23 PM"
  },
  {
   "entry": 60,
   "parent": "xinfeng Zhang",
   "email": "zhxfcn@hotmail.com",
   "phone": "6478818859",
   "student": "Stephan Zhang",
   "prefer": "",
   "medical": "None",
   "initial": "xinfeng Zhang",
   "submitted": "6/24/26, 8:31 PM"
  }
 ]
};
